[package]
name = "raytrace-lm-test"
version = "0.1.0"
authors = ["TheMoogle <gregh203s@gmail.com>", "VirtualBrightPlayz <lego.trains.b@gmail.com>"]
edition = "2021"
resolver = "2"

[dependencies]
wgpu = "0.15"
log = "0.4"
env_logger = "0.10"
# simple async runtime that just blocks (if this is ported to web this needs to be changed to the browser's javascript async runtime)
pollster = "0.3"